apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-personalise
          image: docker.io/glocker1v4/frontend-personalise:v14
          ports:
            - containerPort: 8080
          env:
            - name: VITE_API_URL
              value: "https://backend-personalise-personalise.apps.cluster-2q2cx.2q2cx.sandbox2016.opentlc.com/api"
