apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-personalise
          image: docker.io/glocker1v4/frontend-personalise:v19
          ports:
            - containerPort: 8080
          env:
            - name: VITE_API_URL
              value: "https://backend-personalise-personalise.apps.cluster-68szh.68szh.sandbox2670.opentlc.com/api"
            - name: WEB_URL
              value: "https://frontend-personalise-personalise.apps.cluster-68szh.68szh.sandbox2670.opentlc.com"
